import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);const {PDFDocument,StandardFonts,rgb}=require('pdf-lib');
const paragraphs=[
 ['AVV-Information für die Vorbereitung','Version 13. September 2026'],
 ['Wichtiger Status','Dieses Dokument ist ein veröffentlichter Vertragsentwurf und keine durch den bloßen Abruf abgeschlossene AVV. Vor produktiver Verarbeitung werden Kunde, konkrete Leistung, Weisungswege, Speicher- und Löschfristen und die eingesetzten Dienstleister in der individuellen Vereinbarung vervollständigt.'],
 ['Vertragspartner','Auftraggeber ist der jeweilige Geschäftskunde als Verantwortlicher. Auftragnehmer ist D. Ahlemeyer, Gartenstraße 4, 61267 Neu-Anspach, Deutschland. Datenschutzkontakt: datenschutz@stimmewirkt.de.'],
 ['Gegenstand und Dauer','Stimmewirkt betreibt eine sprechende Webseite anhand bestätigter Unternehmensinformationen. Die Verarbeitung beginnt erst nach Hauptvertrag, individualisierter AVV und bestätigter Freischaltung. Sie endet mit dem Hauptvertrag, vorbehaltlich konkret vereinbarter Rückgabe-, Lösch- und gesetzlicher Aufbewahrungspflichten.'],
 ['Kategorien und Zweck','Zweck sind Besucherfragen aus bestätigtem Unternehmenswissen sowie Einrichtung und Betrieb. Betroffene Personen sind Websitebesucher, Interessenten und berechtigte Ansprechpartner. Datenarten sind Sprach- und Gesprächsinhalte, freiwillige geschäftliche Kontaktdaten, Unternehmenswissen sowie technische Sitzungs-, Verbindungs- und Missbrauchsschutzdaten. Besondere Daten sind nicht Teil der Standardleistung.'],
 ['Technische und organisatorische Maßnahmen','Serverseitige Schlüssel, HTTPS, signierte HttpOnly-Sitzungen für geschützte Bereiche, Rollen- und Mandantenprüfungen, Origin-Prüfungen, atomare Guthabenreservierung und begrenzte öffentliche Demo mit CAPTCHA, IP-, Zeit-, Parallelitäts- und Budgetkontrolle. Zugriffsverwaltung, Backups, Wiederherstellung, Vorfallprozess und Provideraufbewahrung werden vor Vertragsabschluss konkret geprüft.'],
 ['Vorgesehene Unterauftragnehmer','Vercel: Website- und Serverfunktionshosting. Neon: Datenbank des Kundenkerns. OpenAI: Realtime-Verarbeitung freiwilliger Sprache und bestätigten Wissens bei aktiver Sprachfunktion. Resend: transaktionale Systemmails erst nach geprüfter Konfiguration. Für jeden Dienst sind Vertrags-/DPA-Abdeckung, Verarbeitungsorte und konkrete Einstellungen vor Einbeziehung zu prüfen.'],
 ['Einbeziehung, Löschung und Änderungen','Der Kunde erhält die vervollständigte Fassung vor der Freischaltung. Erst dokumentierte Zustimmung und Hauptvertrag beziehen sie ein. Format, Frist, Sicherungskopien und Löschbestätigung werden je Kundenvertrag festgelegt. Neue Unterauftragnehmer oder wesentliche Änderungen werden nicht stillschweigend genehmigt.'],
 ['Kontrolle und Vorfälle','Stimmewirkt unterstützt den Kunden im vereinbarten und rechtlich erforderlichen Umfang bei Betroffenenrechten, Sicherheitsfragen und Datenschutzvorfällen. Nachweise und Kontrollen wahren die Sicherheit und Daten anderer Kunden. Meldepflichten des Verantwortlichen bleiben getrennt.']
];
const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);let page,y;
const newPage=()=>{page=pdf.addPage([595.28,841.89]);y=790;page.drawText('www.stimmewirkt.de · Auftragsverarbeitung', {x:48,y:812,size:8,font,color:rgb(.35,.42,.37)});};
const lines=(text,size=10,width=495)=>{const words=text.split(/\s+/),result=[];let line='';for(const word of words){const candidate=line?line+' '+word:word;if(font.widthOfTextAtSize(candidate,size)>width){result.push(line);line=word;}else line=candidate;}if(line)result.push(line);return result;};
newPage();for(const [heading,text] of paragraphs){const needed=20+lines(text).length*14;if(y-needed<55)newPage();page.drawText(heading,{x:48,y,size:heading===paragraphs[0][0]?22:13,font:heading===paragraphs[0][0]?bold:bold,color:rgb(.12,.24,.2)});y-=heading===paragraphs[0][0]?31:20;for(const line of lines(text)){page.drawText(line,{x:48,y,size:10,font,color:rgb(.23,.29,.25)});y-=14;}y-=12;}
const bytes=await pdf.save();await writeFile(new URL('../avv-stimmewirkt-2026-09-13.pdf',import.meta.url),bytes);
